services:
  naive_proxy:
    image: xia1997x/naive-proxy:latest
    container_name: naive_proxy_ct
    user: 1000:1000
    env_file: naive.env
    ports:
      - "8443:443"
    volumes:
      - ./caddy_data:/naive_base/caddy/
    restart: unless-stopped